### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by sirkitree** [socra/socra-python#3]
I'd like to add some instructions for how to run this as it seems like the 'usage' section is incomplete.

For instance: 
- list what apis are supported
- tell the user how to add an api key
- list a sample command

**Comment by morteymike** [comment]
You're absolutely right, it's incomplete. I went ahead and added a bit to the Usage and other sections to help clarify the initial install and supported providers.

Feel free to open a PR if you'd like me to add some more!

**Comment by sirkitree** [comment]
You commit addressed these, thanks! 

quick tip: in your commit you can state something like 'fixes #3' which will automatically close this issue :)
